openapi: "3.1.0"
info:
  description: |
    # Documentation for the subscription service API
    
    ## Glossary
    
    ### Subscription plan
    
    A subscription plan is a set of features that a user can subscribe to. Each subscription plan has a name, a price and a set of features.
    A subscription plan can inherit features from another subscription plan so that the features do not have to be defined multiple times.
    
    ### Feature
    
    A feature is a part of a subscription plan. Each feature has a name and a description.
    
    ### Subscription
    
    A subscription is a record of a user subscribing to a subscription plan. Each subscription has a start date, an end date and a reference to the subscription plan.
    
    ### User
    
    A user is a person who can subscribe to a subscription plan. 

  version: "1.0.0"
  title: "Subscription service API"
  contact:
    email: "bros@codebros.cz"

  servers:
    - url: "https://sub.codebros.cz/api/v1"
      description: "Dev server"

paths:
